### ISSUE TITLE
NuGet publish?

### ISSUE THREAD

**Issue by JorgenSmith** [faniereynders/aspnetcore-hateoas#1]
Hi Fanie, 
Love your clean work, and the fact that my controllers will need exactly *zero* knowledge of Hateoas config.
It'd be great if you could publish the project as a package to NuGet!

Many thanks, 
Jorgen

**Comment by faniereynders** [comment]
here ya'll go https://www.nuget.org/packages/AspNetCore.Hateoas/

**Comment by monica85rodrigues** [comment]
Nice Job
